Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - seeds/*

Layout/LineLength:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
